Blog.config({
  title: "Raquel San Millan HealthCoach",
  syntaxHighlighting: true,
  syntaxHighlightingTheme: 'github',
  basePath: '/blog',
  adminBasePath: '/adminblog',
  //adminRole: 'blogAdmin',
  //authorRole: 'blogAuthor',
  blogIndexTemplate: 'blog',
  blogShowTemplate: 'show',
  dateFormat: 'YYYY-MM-DD',
  comments: {
    useSideComments: true, // default is false
    allowAnonymous: true   // default is false
    //disqusShortname: 'blogpackage'
  },
  rss: {
    title: 'Blog oficial - Raquel San Millan HealthCoach',
    description: 'Este es el Blog oficial de Raquel San Millan HealthCoach'
  },
  language: {
    blogEmpty: 'No se han encontrado publicaciones.',
    backToBlogIndex: 'Volver a los posts',
    loadMore: 'Cargar siguientes',
    tags: 'Tags',
    slug: 'Slug',
    metaDescription: 'Meta Description',
    body: 'Body',
    showAsVisual: 'Visual',
    showAsHtml: 'HTML',
    save: 'Publicar',
    cancel: 'Cancelar',
    "delete": 'Delete',
    metaAuthorBy: 'By',
    metaAuthorOn: 'on',
    edit: 'Editar',
    areYouSure: 'Estas seguro?',
    disqusPoweredBy: 'comments powered by',
    adminHeader: 'Administración del blog',
    addPost: 'Añadir publicación',
    allPosts: 'Todas los Posts',
    myPosts: 'Mis Posts',
    addPost: 'Añadir Post',
    editPost: 'Editar Post',
    title: 'Titulo',
    author: 'Autor',
    updatedAt: 'Fecha actualización',
    publishedAt: 'Fecha publicación',
    visibleTo: 'Visible para',
    featuredImage: 'Featured Image',
    selectFile: 'Seleccionar archivo',
    imageAsBackground: 'Usar como fondo para el titulo',
    enterTag: 'Añade un tag y pulsa enter',
    postCreateFirst: 'Crea el primer blog',
    postVisibilityAdmins: 'Administradores y yo',
    postVisibilityLink: 'Cualquiera con el link',
    postVisibilityAnyone: 'El mundo',
    saved: 'Guardado',
    editFeaturedImageSaved: 'Featured image saved',
    editErrorSlugExists: 'Blog with this slug already exists',
    editErrorBodyRequired: 'Blog body is required'
  }
});