Blog.config({
  title: "Raquel San Millan HealthCoach",
  syntaxHighlighting: true,
  syntaxHighlightingTheme: 'github',
  basePath: '/blog',
  adminBasePath: '/adminblog',
  //adminRole: 'blogAdmin',
  //authorRole: 'blogAuthor',
  blogIndexTemplate: 'blog',
  blogShowTemplate: 'show',
  dateFormat: 'YYYY-MM-DD',
  //comments: {
  //  disqusShortname: 'blogpackage'
  //},
  rss: {
    title: 'Blog oficial - Raquel San Millan HealthCoach',
    description: 'Este es el Blog oficial de Raquel San Millan HealthCoach'
  },
  language: {
    blogEmpty: 'Aún no hay entradas',
    backToBlogIndex: 'Volver a los posts',
    loadMore: 'Cargar siguientes',
    tags: 'Tags',
    slug: 'Slug',
    metaDescription: 'Meta Description',
    body: 'Body',
    showAsVisual: 'Visual',
    showAsHtml: 'HTML',
    save: 'Publicar',
    cancel: 'Cancel',
    "delete": 'Delete',
    metaAuthorBy: 'By',
    metaAuthorOn: 'on',
    edit: 'Edit',
    areYouSure: 'Estas seguro?',
    disqusPoweredBy: 'comments powered by',
    adminHeader: 'Blog Admin',
    addPost: 'Add Blog Post',
    allPosts: 'All Posts',
    myPosts: 'My Posts',
    addPost: 'Add Post',
    editPost: 'Edit Post',
    title: 'Title',
    author: 'Author',
    updatedAt: 'Updated At',
    publishedAt: 'Published At',
    visibleTo: 'Visible To',
    featuredImage: 'Featured Image',
    selectFile: 'Select File',
    imageAsBackground: 'Use as background for title',
    enterTag: 'Type in a tag & hit enter',
    postCreateFirst: 'Create the first blog',
    postVisibilityAdmins: 'Me & Admins only',
    postVisibilityLink: 'Anyone with link',
    postVisibilityAnyone: 'The world',
    saved: 'Saved',
    editFeaturedImageSaved: 'Featured image saved',
    editErrorSlugExists: 'Blog with this slug already exists',
    editErrorBodyRequired: 'Blog body is required'
  }
});